### ISSUE TITLE
Transform/hide +1/-1 comments

### ISSUE THREAD

**Issue by spenceralger** [staticshowdown/ss15-enhance#29]
+1/-1 comments should show up in the issue page as a facepile, while other comments should show in a timeline. We can still show where people +1'd in the timeline, but they should be mini-facepiles.

**Comment by captainhurst** [comment]
Great work you handsome devils!

**Comment by captainhurst** [comment]
:+1:

**Comment by w33ble** [comment]
we collapse them into smaller collections of users
